apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "massivepinger.fullname" . }}
  labels:
    {{- include "massivepinger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "massivepinger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "massivepinger.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--config"
            - "/config/config.yaml"
            - "--port"
            - "{{ .Values.service.port }}"
          ports:
            - name: metrics
              containerPort: 9123
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9123
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9123
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "massivepinger.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
