name: Helm

on:
  pull_request:
    paths:
      - "helm-chart/**"

jobs:
  helm-lint:
    name: Helm Lint and Template
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v5

      - name: Helm lint
        run: helm lint helm-chart/

      - name: Helm template
        run: helm template massivepinger helm-chart/
